# Generated by Django 5.1.5 on 2025-03-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=20)),
                ('disc', models.CharField(max_length=255)),
                ('aulas', models.IntegerField()),
            ],
        ),
    ]
